### ISSUE TITLE
Usage questions

### ISSUE THREAD

**Issue by davidaray** [DrosophilaGenomeEvolution/TrEMOLO#28]
Thank you for this tool. I'm interested in using it to identify rates of TE polymorphism in paired haplotypes. In other words, I have phased haplotypes of individuals and would like to identify any polymorphisms in the two haplotypes. I have a high quality TE library and both haplotypes, all in .fasta format. Both haplotypes are very high quality.

I can get TrEMOLO to run and I get output, including a TE_INFOs file. However, I'm having difficulty interpreting the output and want to make sure I'm not encountering critical errors. 

For example, I do get an error near completion of the run. 

The run is initiated with: 
```
singularity exec \
	-B $TREMOLODIR:$TREMOLODIR,$WORKDIR:$WORKDIR,$BAT1K:$BAT1K,$DATAFREEZE:$DATAFREEZE \
	$CONTAINER/TrEMOLO.simg snakemake \
	--snakefile $TREMOLODIR/run.snk \
	--configfile $WORKDIR/bin/${SPECIES}_insider_config.yaml
```
The yaml file is as follows:
```

# all path can be relatif or absolute
DATA: 
    REFERENCE:       "/lustre/scratch/daray/bat1k_TE_analyses/tremolo/unzipped_assemblies/mArtIn1.1.hap1.fa"   #reference genome (fasta file) only if INSIDER_VARIANT = True [optional]
    GENOME:          "/lustre/scratch/daray/bat1k_TE_analyses/tremolo/unzipped_assemblies/mArtIn1.1.hap2.fa"      #genome (fasta file) [required]
    WORK_DIRECTORY:  "/lustre/scratch/daray/bat1k_TE_analyses/tremolo/output/mArtIn1"                  #name of output directory [required or empty]
    TE_DB:           "/lustre/scratch/daray/bat1k_TE_analyses/bat1k_named_20241126.fa"      #Database of TE (a fasta file) [required]


CHOICE:
    PIPELINE:
        OUTSIDER_VARIANT: False # D'ont change it
        INSIDER_VARIANT: True   # TE assembled (in genome)
        REPORT: True            # for getting report.html with graph
    OUTSIDER_VARIANT:
        CALL_SV: "sniffles" # possibility (sniffles, svim, no_sniffles) 
        INTEGRATE_TE_TO_GENOME: True # (True, False) Re-build the assembly with insiders integrated in
        CLIPPED_READS: False # (True, False) Processing of clipped reads (SOFT, HARD)
    INSIDER_VARIANT:
        DETECT_ALL_TE: False    # Warning can take long time
    INTERMEDIATE_FILE: True     # to keep the intermediate analysis files to process them. 


PARAMS:
    THREADS: 12 #number of threads for some task
    OUTSIDER_VARIANT:
        MINIMAP2:
            PRESET_OPTION: 'map-ont' # minimap2 preset option is map-ont by default (map-pb, map-ont etc)
            OPTION: '' # more option of minimap2
        SAMTOOLS_VIEW:
            PRESET_OPTION: '' 
        SAMTOOLS_SORT:
            PRESET_OPTION: ''
        SAMTOOLS_CALLMD:
            PRESET_OPTION: ''
        TSD:
            SIZE_FLANK: 20  # flanking sequence size to calculate TSD put value > 4 
        TE_DETECTION:
            CHROM_KEEP: "." # regular expresion of chromosome; exemple  for Drosophila  "[23][RL],4,X" ; Put "." for keep all chromosome
            GET_SEQ_REPORT_OPTION: "-m 30" #option get_seq_vcf.py option du fichier de récupération des séquences dans le vcf
            TIME_LIMIT: 0 # time limit for processing SV detection (rule TrEMOLO_SV_TE); put value >= 0 (hours); 0 means no time limit
        PARS_BLN_OPTION: "--min-size-percent 80 --min-pident 80" # option of TrEMOLO/pipeline/lib/python/parse_blast_main.py  Warning d'ont put -c option
    INSIDER_VARIANT:
        PARS_BLN_OPTION: "--min-size-percent 80 --min-pident 80" 
        MINIMAP2:
            PRESET_OPTION: 'asm5' # minimap2 preset option is asm5 by default (asm5, asm10, asm20 etc)
            OPTION: '--split-prefix tmp_TrEMOLO_split-prefix'
```

The run appears to complete based on line 265 of the output file. See the attached file.

[mArtIn1_TrEMOLO.16020752.txt](https://github.com/user-attachments/files/18812766/mArtIn1_TrEMOLO.16020752.txt)

```
[1] "/lustre/scratch/daray/bat1k_TE_analyses/tremolo/output/mArtIn1/REPORT/mini_report/web/index.html"

DONE NO ERROR DETECTED ✔ 
```
However, shortly after that line, I see this:
```
Lien symbolique créé : /lustre/scratch/daray/bat1k_TE_analyses/tremolo/output/mArtIn1/INPUT/mArtIn1.1.hap1.fa -> /lustre/scratch/daray/bat1k_TE_analyses/tremolo/unzipped_assemblies/mArtIn1.1.hap1.fa
Lien symbolique créé : /lustre/scratch/daray/bat1k_TE_analyses/tremolo/output/mArtIn1/INPUT/mArtIn1.1.hap2.fa -> /lustre/scratch/daray/bat1k_TE_analyses/tremolo/unzipped_assemblies/mArtIn1.1.hap2.fa
CHECKING OF DB TE....



[96m[BEFORE SNK][0m Checking of the existence of all parameters...
[92mCHOICE: ✔ [0m
[92mPIPELINE: ✔ [0m
[92mOUTSIDER_VARIANT: ✔ [0m
[92mINSIDER_VARIANT: ✔ [0m
[92mREPORT: ✔ [0m
[92mOUTSIDER_VARIANT: ✔ [0m
[92mCALL_SV: ✔ [0m
[92mINTEGRATE_TE_TO_GENOME: ✔ [0m
[92mCLIPPED_READS: ✔ [0m
[92mINSIDER_VARIANT: ✔ [0m
[92mDETECT_ALL_TE: ✔ [0m
[92mINTERMEDIATE_FILE: ✔ [0m
[92mPARAMS: ✔ [0m
[92mTHREADS: ✔ [0m
[92mOUTSIDER_VARIANT: ✔ [0m
[92mMINIMAP2: ✔ [0m
[92mPRESET_OPTION: ✔ [0m
[92mOPTION: ✔ [0m
[92mSAMTOOLS_VIEW: ✔ [0m
[92mPRESET_OPTION: ✔ [0m
[92mSAMTOOLS_SORT: ✔ [0m
[92mPRESET_OPTION: ✔ [0m
[92mSAMTOOLS_CALLMD: ✔ [0m
[92mPRESET_OPTION: ✔ [0m
[92mTSD: ✔ [0m
[92mSIZE_FLANK: ✔ [0m
[92mTE_DETECTION: ✔ [0m
[92mCHROM_KEEP: ✔ [0m
[92mGET_SEQ_REPORT_OPTION: ✔ [0m
[92mTIME_LIMIT: ✔ [0m
[92mPARS_BLN_OPTION: ✔ [0m
[92mINSIDER_VARIANT: ✔ [0m
[92mPARS_BLN_OPTION: ✔ [0m
[92mMINIMAP2: ✔ [0m
[92mPRESET_OPTION: ✔ [0m
[92mOPTION: ✔ [0m

AN ERROR OCCURRED !!
```

So, I can't tell if an error occurred or not. What is happening to produce this error message?

Another thing that makes me suspicious of the results is that the report.html appears malformed. In your example, there are five categories of output, Resume parameters, Timeline, INSIDER, OUTSIDER, and INSIDER AND OUTSIDER GROUPED. As you will see from the image attached, The latter two are missing from my report file.

![Image](https://github.com/user-attachments/assets/75ac34af-66ed-4361-a77e-6bedbb4bf7ad)

It appears that the pipeline is failing after the first module, INSIDER. 

I do see an error in the other output file that could indicate the problem. See line 17. 

[mArtIn1_TrEMOLO.16020752.err.txt](https://github.com/user-attachments/files/18812792/mArtIn1_TrEMOLO.16020752.err.txt)

However, it's unclear what this means.

Any help would be appreciated.

David
